name: 'OpenTofu Cleanup'

on:
  workflow_dispatch:  # Manual trigger button

env:
  AWS_REGION: eu-north-1

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d  # v6.2.2
        with:
          role-to-assume: arn:aws:iam::936777225880:role/GitHubActionsTerraformApply
          aws-region: ${{ env.AWS_REGION }}

      - name: OpenTofu - Setup Tofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4  # v2.0.2
        with:
          tofu_version: '1.11.2'

      - name: Execute OpenTofu init in envs/test
        working-directory: envs/test
        run: |
          tofu init

      - name: Execute OpenTofu Destroy in envs/test
        working-directory: envs/test
        run: |
          tofu destroy -auto-approve
